-- Ajouter une politique pour permettre l'insertion de phrases (admin ou service role)
-- Exécutez ce script dans le SQL Editor de Supabase

-- Option 1: Permettre l'insertion publique pour les sentences (plus simple pour le développement)
CREATE POLICY "Allow public insert on sentences" ON sentences
  FOR INSERT WITH CHECK (true);

-- Vous pouvez aussi insérer les données directement ici:
INSERT INTO sentences (langue_source, langue_cible, phrase_originale, theme_grammatical, niveau) VALUES
  ('Français', 'Anglais', 'Les tensions géopolitiques entre la Chine et les États-Unis s''intensifient dans le domaine technologique.', 'Present continuous, Passive voice, Complex sentence structure', 'C1'),
  ('Français', 'Anglais', 'L''Union européenne cherche à renforcer son autonomie stratégique face aux défis mondiaux.', 'Present simple, Infinitive of purpose, Complex noun phrases', 'B2'),
  ('Français', 'Anglais', 'Le commerce international représente une part croissante de l''économie mondiale malgré les tensions protectionnistes.', 'Present simple, Despite + noun, Adjectives of degree', 'B2'),
  ('Français', 'Anglais', 'Les migrations internationales constituent un défi majeur pour les politiques européennes d''intégration.', 'Present simple, For + noun, Compound nouns', 'C1'),
  ('Français', 'Anglais', 'L''intelligence artificielle transforme radicalement les modèles économiques traditionnels.', 'Present continuous, Adverbs, Complex object', 'B2'),
  ('Français', 'Anglais', 'Les investissements verts représentent un enjeu majeur pour la transition écologique.', 'Present simple, Complex noun phrases, Prepositions', 'B2'),
  ('Français', 'Anglais', 'La croissance économique dépend largement des investissements dans l''éducation et la recherche.', 'Present simple, On + noun, Adverbs of manner', 'B2'),
  ('Français', 'Anglais', 'L''enseignement à distance transforme les méthodes pédagogiques traditionnelles.', 'Present continuous, Gerunds, Complex objects', 'B2'),
  ('Français', 'Anglais', 'La diversité culturelle enrichit le tissu social des métropoles modernes.', 'Present simple, Complex noun phrases, Prepositions', 'B2'),
  ('Français', 'Anglais', 'La cohésion sociale nécessite des politiques publiques inclusives pour tous les citoyens.', 'Present simple, For + plural noun, Adjectives', 'B2'),
  ('Français', 'Anglais', 'Les progrès de l''intelligence artificielle soulèvent des questions éthiques complexes.', 'Present simple, Passive voice, Complex adjectives', 'B2'),
  ('Français', 'Anglais', 'Les réseaux sociaux ont révolutionné la façon dont nous communiquons et partageons l''information.', 'Present perfect, Relative clauses, Have/has + past participle', 'B2'),
  ('Français', 'Anglais', 'Le big data offre de nouvelles opportunités pour l''analyse prédictive dans de nombreux secteurs.', 'Present simple, For + noun, In + plural noun', 'C1'),
  ('Français', 'Anglais', 'Le changement climatique représente la plus grande menace pour l''humanité au 21ème siècle.', 'Present simple, Superlative adjectives, Ordinal numbers', 'B2'),
  ('Français', 'Anglais', 'Les énergies renouvelables deviennent progressivement plus compétitives sur le marché mondial.', 'Present continuous, Comparative adverbs, Complex noun phrases', 'C1'),
  ('Français', 'Anglais', 'La perte de biodiversité constitue un risque majeur pour l''équilibre des écosystèmes terrestres.', 'Present simple, For + noun, Of + noun', 'C1'),
  ('Français', 'Anglais', 'La télémédecine offre de nouvelles possibilités pour améliorer l''accès aux soins médicaux.', 'Present simple, Gerunds, Infinitive of purpose', 'B2'),
  ('Français', 'Anglais', 'La pandémie de COVID-19 a profondément transformé nos habitudes quotidiennes et nos comportements sociaux.', 'Present perfect, Adverbs of manner, Compound nouns', 'B2'),
  ('Français', 'Anglais', 'La prévention des maladies cardiovasculaires passe par une alimentation équilibrée et l''exercice physique régulier.', 'Present simple, Of + noun, And + noun', 'B2'),
  ('Français', 'Anglais', 'La démocratie représentative nécessite une participation active des citoyens pour fonctionner efficacement.', 'Present simple, Infinitive of purpose, Adjectives', 'B2'),
  ('Français', 'Anglais', 'Les organisations internationales jouent un rôle crucial dans la résolution des conflits mondiaux.', 'Present simple, Gerunds, Adjectives of degree', 'B2'),
  ('Français', 'Anglais', 'La gouvernance mondiale nécessite une coopération accrue entre les nations pour faire face aux défis globaux.', 'Present simple, Between + plural noun, Infinitive of purpose', 'C1'),
  ('Français', 'Anglais', 'La formation continue est devenue essentielle dans un monde où les compétences évoluent rapidement.', 'Present perfect, Relative clauses, Adverbs', 'B2'),
  ('Français', 'Anglais', 'L''éducation inclusive vise à garantir que tous les élèves puissent bénéficier d''une éducation de qualité.', 'Present simple, Infinitive of purpose, Modal verbs', 'B2'),
  ('Français', 'Anglais', 'L''apprentissage en ligne offre une flexibilité accrue pour les étudiants de tous âges et origines.', 'Present simple, For + noun, Of + plural noun', 'B2'),
  ('Français', 'Anglais', 'Les arts numériques combinent créativité artistique et technologies modernes pour créer de nouvelles formes d''expression.', 'Present simple, Infinitive of purpose, Compound nouns', 'C1'),
  ('Français', 'Anglais', 'Le patrimoine culturel doit être préservé pour les générations futures malgré les défis de la mondialisation.', 'Modal verbs, Passive voice, Despite + noun', 'C1'),
  ('Français', 'Anglais', 'Les industries culturelles contribuent significativement à l''économie créative et à l''emploi dans de nombreux pays.', 'Present simple, To + noun, In + plural noun', 'C1'),
  ('Français', 'Anglais', 'La mobilité urbaine durable nécessite une coordination entre transport public et véhicules individuels.', 'Present simple, Gerunds, Between + plural nouns', 'B2'),
  ('Français', 'Anglais', 'L''industrie du transport aérien fait face à des défis importants liés à la réduction des émissions de CO2.', 'Present simple, Past participles as adjectives, Related to + noun', 'C1'),
  ('Français', 'Anglais', 'La recherche scientifique fondamentale constitue la base de l''innovation technologique future.', 'Present simple, Complex noun phrases, Ordinal numbers', 'C1'),
  ('Français', 'Anglais', 'Les avancées en biotechnologie ouvrent de nouvelles perspectives pour la médecine personnalisée.', 'Present simple, Adjectives, For + noun (purpose)', 'C1'),
  ('Français', 'Anglais', 'Le commerce électronique a transformé les habitudes de consommation des citoyens européens.', 'Present perfect, Possessive case, Compound nouns', 'B2'),
  ('Français', 'Anglais', 'Les cryptomonnaies représentent un défi majeur pour les régulateurs financiers mondiaux.', 'Present simple, Adjectives of degree, For + noun', 'C1'),
  ('Français', 'Anglais', 'Les plateformes numériques transforment les modèles économiques traditionnels dans de nombreux secteurs.', 'Present continuous, Adjectives, In + plural noun', 'B2'),
  ('Français', 'Anglais', 'Le télétravail est devenu une norme dans de nombreux secteurs professionnels depuis la pandémie.', 'Present perfect, Adjectives, Since + noun', 'B2'),
  ('Français', 'Anglais', 'L''écart salarial entre hommes et femmes persiste malgré les efforts législatifs.', 'Present simple, Despite + noun, Compound nouns', 'B2'),
  ('Français', 'Anglais', 'La formation professionnelle continue est essentielle pour s''adapter aux changements technologiques.', 'Present simple, To + infinitive, Adjectives', 'B2'),
  ('Français', 'Anglais', 'La désinformation en ligne constitue une menace sérieuse pour la démocratie moderne.', 'Present simple, Adjectives, To + noun', 'B2'),
  ('Français', 'Anglais', 'Les plateformes de streaming ont révolutionné l''industrie du divertissement traditionnel.', 'Present perfect, Adjectives, Compound nouns', 'B2'),
  ('Français', 'Anglais', 'Les réseaux sociaux influencent considérablement l''opinion publique et les comportements électoraux.', 'Present simple, Adverbs, And + noun', 'B2'),
  ('Français', 'Anglais', 'La cybersécurité est devenue une priorité nationale pour la plupart des gouvernements européens.', 'Present perfect, Adjectives, For + plural noun', 'C1'),
  ('Français', 'Anglais', 'L''intelligence artificielle militaire soulève des questions éthiques complexes sur l''autonomie des armes.', 'Present simple, Adjectives, About + noun', 'C1'),
  ('Français', 'Anglais', 'La lutte contre le terrorisme international nécessite une coopération étroite entre les services de renseignement.', 'Present simple, Against + noun, Between + plural noun', 'C1'),
  ('Français', 'Anglais', 'Les villes durables intègrent des solutions innovantes pour réduire leur impact environnemental.', 'Present simple, Infinitive of purpose, Possessive adjectives', 'C1'),
  ('Français', 'Anglais', 'La transition vers la mobilité électrique nécessite des investissements massifs dans les infrastructures.', 'Present simple, To + noun, In + noun', 'C1'),
  ('Français', 'Anglais', 'La transition énergétique représente un défi majeur pour les économies développées.', 'Present simple, Adjectives, For + plural noun', 'B2'),
  ('Français', 'Anglais', 'L''énergie éolienne offshore offre un potentiel considérable pour la production d''électricité renouvelable.', 'Present simple, Adjectives, For + noun', 'C1'),
  ('Français', 'Anglais', 'L''État de droit constitue la base de toute démocratie moderne et stable.', 'Present simple, Of + noun, And + adjective', 'C1'),
  ('Français', 'Anglais', 'Les tribunaux internationaux jouent un rôle essentiel dans la résolution des conflits armés.', 'Present simple, In + gerund, Compound nouns', 'C1'),
  ('Français', 'Anglais', 'La protection des droits humains représente un défi permanent dans un monde globalisé.', 'Present simple, Of + noun, In + noun', 'C1');
